[tool.black]
line-length = 100


[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I", "N", "D", "UP", "B", "C4", "T20", "SIM", "PL"]
ignore = ["D100", "D101", "D102", "D103", "D107"]


[tool.pyright]
typeCheckingMode = "basic"
pythonVersion = "3.12"
include = ["."]
exclude = ["__pycache__", "build", "dist"]
