version = 0.1

[ingest_options.deploy.parameters]
stack_name = "strategy-tester-options"
s3_bucket = "option-strategy-tester"
s3_prefix = "strategy-tester-options"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "function=\"ingest_options\""
env_file = "env.options.json"

[ingest_snapshots.deploy.parameters]
stack_name = "strategy-tester-snapshots"
s3_bucket = "option-strategy-tester"
s3_prefix = "strategy-tester-snapshots"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
tags = "function=\"ingest_snapshots\""
env_file = "env.snapshots.json"

