version = 0.1

# Default profile for 'sam deploy'
[default.deploy.parameters]
stack_name = "strategy-tester"
s3_bucket = "YOUR_S3_BUCKET_NAME" 
s3_prefix = "strategy-tester"
region = "us-east-1" 
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default.build.parameters]
cached = true
parallel = true

[ingest_options.invoke.parameters]
event = "events/event.json"
env_vars = ".env.options" 

[ingest_snapshots.invoke.parameters]
event = "events/event.json"
env_vars = ".env.snapshots"
