service: strategy-tester

frameworkVersion: '*'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    POLYGON_API_KEY: ${env:POLYGON_API_KEY}

functions:
  processOptions:
    handler: handler.lambda_handler
    timeout: 300 # 5 minutes
    memorySize: 512
    events:
      - schedule: rate(1 day) # Run once per day
      - http:
          path: process-options
          method: get

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    noDeploy:
      - pytest
      - pytest-cov
  serverless-offline:
    httpPort: 12000
    lambdaPort: 12001