from __future__ import annotations
from typing import Any

class Prisma:
    def __init__(self, auto_register: bool = ...) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...

class Json(dict[str, Any]):
    ...
